"""Write docs/example_request.md: a real /v1/systemone request for each category scheme, with nimble's
response and the decoded result.

  python -m sidm.example_doc                  # rebuild the doc from cached responses (no model calls)
  python -m sidm.example_doc --call embedded  # call nimble for these schemes and cache the responses

Responses are cached in docs/example_responses/<scheme>.json, so the doc can be rebuilt without nimble.
"""
import argparse
import json
from pathlib import Path

from sidm.ollama_client import system_one
from sidm.parser import DEFAULT_SCHEME, ROLE_GUIDE, SCHEMES, build_request, decode

QUERY = "grey oak coffee table with storage cheap"
DOC = Path("docs/example_request.md")
CACHE = Path("docs/example_responses")

SCHEME_NOTES = {
    "router": "Top-level question `cat_L1` (6 groups + `none`), then one *conditional* question per group "
              "(\"if tables is searched, which type?\") that must pick a type of that group.",
    "embedded": "No `cat_L1`. Every group question can answer `other_product` (\"not this group\"), so the group "
                "decision happens inside the group questions; 'no category' = no group claims the query.",
}


def _round(resp):
    for a in resp["answers"].values():
        a["probabilities"] = {k: round(v, 4) for k, v in a["probabilities"].items()}
        a["confidence"] = round(a["confidence"], 4)
    return resp


def call(scheme):
    state, questions, _ = build_request(QUERY, scheme)
    resp, latency = system_one("nimble", state, questions)
    CACHE.mkdir(parents=True, exist_ok=True)
    (CACHE / ("%s.json" % scheme)).write_text(json.dumps({"latency_s": latency, "response": _round(resp)}, indent=1))


def scheme_section(scheme):
    state, questions, tokens = build_request(QUERY, scheme)
    request = {"model": "nimble", "state": state, "questions": questions, "keep_alive": "30m"}
    out = ["## Scheme `%s`%s" % (scheme, " (default)" if scheme == DEFAULT_SCHEME else ""), "",
           SCHEME_NOTES[scheme], "",
           "The request has %d questions (%d word questions) and is %d bytes of JSON." % (
               len(questions), len(tokens), len(json.dumps(request))), "",
           "| Question | Options | First options |", "|---|---|---|"]
    for name, q in questions.items():
        if name.startswith("word_") and name != "word_1":
            continue
        keys = list(q["criteria"])
        label = name if not name.startswith("word_") else "word_1 … word_%d" % len(tokens)
        out.append("| `%s` | %d | %s |" % (label, len(keys), ", ".join("`%s`" % k for k in keys[:5]) + (" …" if len(keys) > 5 else "")))
    out += ["", "### Request", "```json", json.dumps(request, indent=1), "```", ""]
    cached = CACHE / ("%s.json" % scheme)
    if cached.exists():
        c = json.loads(cached.read_text())
        resp = c["response"]
        dec = decode(resp, tokens, scheme)
        out += ["### Response", "Latency %.2f s; server-reported usage %s." % (c["latency_s"], resp.get("usage")),
                "```json", json.dumps(resp, indent=1), "```", "",
                "### Decoded result (tuned decoding)", "```json",
                json.dumps({k: dec[k] for k in ("category", "filters", "token_labels", "residual_tokens")}, indent=1),
                "```", ""]
    else:
        out += ["### Response", "*Not recorded yet:* run `uv run python -m sidm.example_doc --call %s` "
                "when nimble is free (not while dataset generation runs)." % scheme, ""]
    return out


def build():
    lines = ["# Example `/v1/systemone` request", "",
             "Query: **`%s`**, sent to a local Ollama 0.35 running `nimble`. Requests are built by "
             "`build_request()` in `src/sidm/parser.py`; this file is generated by `python -m sidm.example_doc`." % QUERY,
             "", "Both schemes share `state` and the filter and word questions; they differ only in the category "
             "questions (`cat_*`).", "",
             "## Word roles prompt (in `state`, shared)", "", "> " + ROLE_GUIDE, ""]
    for scheme in [DEFAULT_SCHEME] + [s for s in SCHEMES if s != DEFAULT_SCHEME]:
        lines += scheme_section(scheme)
    DOC.write_text("\n".join(lines))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--call", nargs="*", default=[], choices=sorted(SCHEMES), help="schemes to (re)call nimble for")
    args = ap.parse_args()
    for scheme in args.call:
        call(scheme)
    build()
    print("written %s" % DOC)


if __name__ == "__main__":
    main()
